import asyncio
import logging

from backend.state import GraphState, PlannerOutput
from backend.orchestration.factory import AgentFactory

logger = logging.getLogger(__name__)

async def router_node(state: GraphState) -> GraphState:
    """
    Router Node: Executes the plan generated by the Planner.
    Runs agents sequentially or in parallel based on `plan.parallel`.
    
    Returns partial state updates (agent_results, entity_store, parsed_document, etc.)
    """
    plan_dict = state.get("plan")
    if not plan_dict:
        logger.error("Router triggered but no plan in state.")
        return {"error": "No execution plan found"}
        
    try:
        plan = PlannerOutput.from_dict(plan_dict)
    except Exception as e:
        logger.error(f"Invalid plan dictionary: {e}")
        return {"error": f"Failed to parse plan: {e}"}

    agents_to_run = plan.agents
    logger.info(f"Router executing agents: {agents_to_run} (parallel={plan.parallel})")
    
    agent_results = []
    
    # Pre-hydration: For doc_parser, if it runs sequentially BEFORE other agents,
    # its outputs (entity_store) become available to subsequent agents.
    
    if plan.parallel and len(agents_to_run) > 1:
        # Run agents concurrently
        tasks = []
        for agent_name in agents_to_run:
            agent = AgentFactory.get_agent(agent_name)
            tasks.append(agent.run(state))
            
        results = await asyncio.gather(*tasks)
        agent_results = [r.to_dict() for r in results]
    else:
        # Run sequentially
        current_state = state.copy()
        
        for agent_name in agents_to_run:
            agent = AgentFactory.get_agent(agent_name)
            
            # If the plan gave us a rewritten query, use it in this local state copy.
            # E.g., RAG might need a specific policy search instead of the raw user query.
            agent_query = getattr(plan.queries, agent_name, None)
            if agent_query:
                # the state expects a dict here because it was serialized
                current_state["plan"]["queries"][agent_name] = agent_query
                
            result = await agent.run(current_state)
            agent_results.append(result.to_dict())
            
            # Post-run integration for Sequential flows (DocParser handoffs)
            if agent_name == "doc_parser" and result.success and result.structured_data:
                # E.g. Update state so SQL agent running next can use entity_store
                # The doc_parser_agent itself populates entity_store in its metadata (or structured_data)
                
                # Update current_state for the next agent
                if "parsed_document" in current_state:
                    current_state["parsed_document"] = result.structured_data
                    
                if "entity_store" in result.metadata:
                    if "entity_store" not in current_state:
                        current_state["entity_store"] = {}
                    current_state["entity_store"].update(result.metadata["entity_store"])

    # Router returns the results. 
    # State additions like parsed_document should be returned so LangGraph persists them.
    update = {"agent_results": agent_results}
    
    # We need to extract any state updates that happened during sequential execution
    # (like doc_parser populating entity_store). Since we only ran it on `current_state`,
    # let's grab what changed and push it to the main state graph.
    if not plan.parallel:
        for result_dict in agent_results:
            if result_dict["agent_name"] == "doc_parser" and result_dict["success"]:
                meta = result_dict.get("metadata", {})
                if "entity_store" in meta:
                    update["entity_store"] = meta["entity_store"]
                if result_dict.get("structured_data"):
                    update["parsed_document"] = result_dict["structured_data"]
                    update["uploaded_file_path"] = None  # Clear the upload so it isn't parsed again
    
    # Since route_after_planner bypasses the router for 0 agents,
    # if we reach this point, we know len(agents_to_run) > 0.
    # If there is exactly 1 agent, we skip the combiner, so we populate `final_answer` here.
    if len(agents_to_run) == 1 and agent_results:
        # Exactly one agent invoked, use its answer directly
        final_ans = agent_results[0].get("answer", "")
        update["final_answer"] = final_ans
        update["previous_turn"] = {"query": state["query"], "answer": final_ans}
        
    return update
